### ISSUE TITLE
ImportError: The ``fake-factory`` package is now called ``Faker``

### ISSUE THREAD

**Issue by unnat** [hjalti/mossum#3]
https://github.com/FactoryBoy/factory_boy/issues/334
Deals with the renaming of fake-factory to Faker. Would
be great if you fix the setup.py file accordingly.

Thanks.

**Comment by unnat** [comment]
https://github.com/FactoryBoy/factory_boy/commit/dba31e3866cdefde1d7f37fc7f0553a12feeab9b deals with something similar.

**Comment by jdestefani** [comment]
The issue can be solved by changing [line 19 of setup.py](https://github.com/hjalti/mossum/blob/master/setup.py#L19) from `"fake-factory>=0.4.2",` to `"Faker>=0.4.2",`

**Comment by hjalti** [comment]
This has been fixed now. Thanks for letting me know :)
